### ISSUE TITLE
ToC crashes when there are no headers/titles

### ISSUE THREAD

**Issue by traverseda** [lepture/mistune-contrib#18]
You can reproduce this by simply trying to render and empty string with the ToC enabled.

```
Traceback (most recent call last):   

[... django stuff ...]
          
  File "/home/alex/projects/MfD-wiki/core/models.py", line 45, in save    
    self.renderedToC = toc.render_toc(level=3)                            
  File "/home/alex/.local/lib/python3.6/site-packages/mistune_contrib/toc.py", line 45, in render_toc                                                
    return ''.join(self._iter_toc(level))                                 
  File "/home/alex/.local/lib/python3.6/site-packages/mistune_contrib/toc.py", line 80, in _iter_toc                                                 
    while last_level > first_level:  
TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'
```

**Comment by lepture** [comment]
fixed by https://github.com/lepture/mistune-contrib/pull/21
